import type { WebProject } from '@/types';

export const webProjects: WebProject[] = [
    {
        id: 'web-1',
        name: 'SIFSA',
        type: 'project',
        status: 'En Desarrollo',
        assigneeId: 'user-1',
        technologies: ['Next.js', 'TailwindCSS'],
        dueDate: '2024-10-15',
    },
    {
        id: 'web-2',
        name: 'PERFUMES',
        type: 'project',
        status: 'Finalizado',
        assigneeId: 'user-2',
        technologies: ['React', 'Firebase'],
        dueDate: '2024-06-30',
        liveUrl: 'https://example.com',
    },
    {
        id: 'web-3',
        name: 'LEATHER',
        type: 'project',
        status: 'Pausado',
        assigneeId: 'user-1',
        technologies: ['HTML', 'CSS'],
        dueDate: null,
    },
     {
        id: 'web-4',
        name: 'alpha jardin',
        type: 'retainer',
        status: 'Mantenimiento',
        assigneeId: 'user-3',
        technologies: ['Wordpress'],
        dueDate: '2024-12-31',
    },
    {
        id: 'web-5',
        name: 'core y niu',
        type: 'retainer',
        status: 'Mantenimiento',
        assigneeId: 'user-3',
        technologies: ['Shopify'],
        dueDate: '2024-12-31',
    },
    {
        id: 'web-6',
        name: 'dc solutions',
        type: 'retainer',
        status: 'Mantenimiento',
        assigneeId: 'user-2',
        technologies: ['Next.js', 'Firebase'],
        dueDate: '2024-12-31',
    },
    {
        id: 'web-7',
        name: 'SIMTEX',
        type: 'project',
        status: 'En Desarrollo',
        assigneeId: 'user-1',
        technologies: ['Next.js', 'TailwindCSS'],
        dueDate: '2024-11-01',
    },
    {
        id: 'web-8',
        name: 'COLOQUIOS',
        type: 'project',
        status: 'Finalizado',
        assigneeId: 'user-4',
        technologies: ['React'],
        dueDate: '2024-05-20',
    },
];
